baseURL = "https://www.activedefense.co.jp/"
title = "株式会社アクティブディフェンス研究所"
theme = "mainroad"
DefaultContentLanguage = "jp"
copyright = "Active Defense Institute, Ltd. 2018"
googleAnalytics = "UA-87477072-1"
paginate = "10"

[params]
  email = "info@activedefense.co.jp"
  subtitle = "攻めの情報セキュリティR&Dチーム"
  postSections = ["news"]
  copyright = "Active Defense Institute, Ltd. 2018"
  description = """
  株式会社アクティブディフェンス研究所は、サイバーセキュリティに関する攻撃・防御技術の研究と自社サービス開発をコア事業とするベンチャー企業です。
  最新のマルウェア対策研究、マルウェア自動解析、マルウェアを用いたサイバー攻撃の脅威情報収集、IoTセキュリティ診断を継続的に知的好奇心ドリブンで取り組んでいます。
  また、そのノウハウを活かし、各種コンサルティングやトレーニング、マルウェアフォレンジックや脆弱性診断・ペネトレーションテストなどを実施しております。
  """
  [params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
  # Client section
  [params.clients_list]
    enable = true

    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    [[params.clients]]
      logo = "aqutras.png"
      link = "http://www.aqutras.com/"
    [[params.clients]]
      logo = "secure-cycle.png"
      link = "https://secure-cycle.co.jp/"

  # Contact section
  [params.contact]
    enable = true
    title = "お問い合わせフォーム"
    subtitle  = "案件のご相談、お見積もりはこちら"
    buttonText = "送信"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "社名とご担当者名（必須）"
      pre = "株式会社アクティブディフェンス研究所 忠鉢 洋輔"
      warning = "社名とご担当者名をご入力ください。"

    [params.contact.form.email]
      text = "メールアドレス（必須）"
      pre = "info@activedefense.co.jp"
      warning = "emailアドレスを入力してください。"

    [params.contact.form.phone]
      text = "電話番号（任意）"
      pre = ""
      warning = "電話番号をご入力ください。"

    [params.contact.form.message]
      text = "ご相談内容をご入力ください（必須）"
      pre = ""
      warning = "ご相談内容をご入力ください。"

[menu]
  [[menu.main]]
    identifier = "top"
    name = "top"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -200

  [[menu.main]]
    identifier = "news"
    name = "ニュース"
    pre = "<i class='fa fa-heart'></i>"
    url = "/news/"
    weight = -190

  [[menu.main]]
    identifier = "consultingetc"
    name = "診断・コンサル・セミナー"
    pre = "<i class='fa fa-heart'></i>"
    url = "/consultingetc/"
    weight = -180


  [[menu.main]]
    identifier = "services"
    name = "サービス"
    pre = "<i class='fa fa-heart'></i>"
    url = "/services/"
    weight = -170

  #[[menu.main]]
    #identifier = "research"
    #name = "研究活動"
    #pre = "<i class='fa fa-heart'></i>"
    #url = "/research/"
    #weight = -160

  [[menu.main]]
    identifier = "partners"
    name = "パートナーシップ"
    pre = "<i class='fa fa-heart'></i>"
    url = "/partners/"
    weight = -160

  [[menu.main]]
    identifier = "company"
    name = "会社情報"
    pre = "<i class='fa fa-heart'></i>"
    url = "/company/"
    weight = -150


  [[menu.main]]
    name = "お問い合わせ"
    pre = "<i class='fa fa-road'></i>"
    url = "/contacts/"
    weight = -100

